# Generated by Django 3.2.9 on 2022-01-10 16:48

import api.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('uid', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('password', models.TextField()),
                ('passoutYear', models.PositiveIntegerField(default=2022, validators=[django.core.validators.MinValueValidator(1984), api.models.max_value_current_year])),
                ('branch', models.CharField(max_length=20)),
                ('skills', models.TextField(blank=True)),
                ('workExperience', models.TextField(blank=True)),
                ('linkedInProfile', models.CharField(blank=True, max_length=100)),
                ('githubProfile', models.CharField(blank=True, max_length=100)),
                ('otherLinks', models.TextField(blank=True)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('currentCompany', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField()),
                ('role', models.CharField(blank=True, max_length=30)),
                ('profilePic', models.ImageField(blank=True, upload_to='profilePics')),
            ],
        ),
    ]
