# Generated by Django 3.2.9 on 2022-01-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220114_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('shortDesc', models.CharField(max_length=50)),
                ('formLink', models.CharField(max_length=50)),
                ('longDesc', models.TextField()),
                ('image', models.ImageField(upload_to='projects')),
            ],
        ),
    ]
