# Generated by Django 3.2.9 on 2022-01-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('package', models.CharField(max_length=20)),
                ('descOfRole', models.TextField()),
                ('tech', models.BooleanField(default=False)),
            ],
        ),
    ]
