# Generated by Django 3.2.9 on 2022-01-14 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='date',
            field=models.DateField(default=datetime.date(2022, 1, 14)),
        ),
    ]
