# Generated by Django 3.2.9 on 2022-01-17 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_question_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='workExperience',
        ),
        migrations.AddField(
            model_name='profile',
            name='pcompany1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='pcompany2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='pcompany3',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='prole1',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='prole2',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='prole3',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
