# Generated by Django 3.2.9 on 2022-02-03 12:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20220118_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='resources',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.DateField(default=datetime.date(2022, 2, 3)),
        ),
    ]
