# Generated by Django 3.2.9 on 2022-02-03 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20220203_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='resources',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
