# Generated by Django 3.2.9 on 2022-02-21 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_event_resources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='formLink',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='shortDesc',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.DateField(default=datetime.date(2022, 2, 21)),
        ),
    ]
